CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR (50) NOT NULL,
password VARCHAR (100) NOT NULL
);

CREATE TABLE employees (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
address VARCHAR(255) NOT NULL,
salary INT (10) NOT NULL
);