<?php
// Lab 2: Secure Token Generation for Password Reset

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $email = trim($_POST['email'] ?? '');
    
    if (!empty($email)) {
        // Generate secure token
        $timestamp = time();
        $token_data = $email . $timestamp;
        $token = md5($token_data);
        
        echo "<h2>Password Reset Token Generated</h2>";
        echo "<p><strong>Email:</strong> " . $email . "</p>";
        echo "<p><strong>Timestamp:</strong> " . $timestamp . "</p>";
        echo "<p><strong>Token:</strong> " . $token . "</p>";
        echo "<p><strong>Reset URL:</strong> reset-password.php?token=" . $token . "&email=" . urlencode($email) . "</p>";
        echo "<p><em>Note: The token is generated by concatenating email with timestamp and hashing using MD5.</em></p>";
    }
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Lab 2 - Password Reset</title>
</head>
<body>
    <h1>Generate Password Reset Token</h1>
    <form method="post">
        <p>Email: <input type="email" name="email" required></p>
        <p><input type="submit" value="Generate Token"></p>
    </form>
</body>
</html>